// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByeV7eNaQdq4oazQJYVBYfsmX4WekWD9w',
    appId: '1:995658958410:web:ed6771f67a71849b1848b3',
    messagingSenderId: '995658958410',
    projectId: 'taxi-app-7364d',
    authDomain: 'taxi-app-7364d.firebaseapp.com',
    storageBucket: 'taxi-app-7364d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0p5nEsZw89GWMljkVTnuajyVmIv5khDE',
    appId: '1:995658958410:android:c47dbe470a57d1211848b3',
    messagingSenderId: '995658958410',
    projectId: 'taxi-app-7364d',
    storageBucket: 'taxi-app-7364d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLBAHxngj5cY8a_cZpFt5jGSKjltPWPTU',
    appId: '1:995658958410:ios:4544ba01610799061848b3',
    messagingSenderId: '995658958410',
    projectId: 'taxi-app-7364d',
    storageBucket: 'taxi-app-7364d.appspot.com',
    iosBundleId: 'com.bns.taxi-app',
  );
}
